version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: py37_integ
      buildspec: codebuild/py37/integ.yml
    - identifier: py37_examples
      buildspec: codebuild/py37/examples.yml

    - identifier: py38_integ 
      buildspec: codebuild/py38/integ.yml
    - identifier: py38_examples
      buildspec: codebuild/py38/examples.yml

    - identifier: py39_integ
      buildspec: codebuild/py39/integ.yml
    - identifier: py39_examples
      buildspec: codebuild/py39/examples.yml

    - identifier: code_coverage
      buildspec: codebuild/coverage.yml
