version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: py38_integ 
      buildspec: codebuild/py38/integ.yml
    - identifier: py38_examples
      buildspec: codebuild/py38/examples.yml

    - identifier: py39_integ
      buildspec: codebuild/py39/integ.yml
    - identifier: py39_examples
      buildspec: codebuild/py39/examples.yml

    - identifier: py310_integ
      buildspec: codebuild/py310/integ.yml
    - identifier: py310_examples
      buildspec: codebuild/py310/examples.yml

    - identifier: py311_integ
      buildspec: codebuild/py311/integ.yml
    - identifier: py311_examples
      buildspec: codebuild/py311/examples.yml

    - identifier: py312_integ
      buildspec: codebuild/py312/integ.yml
    - identifier: py312_examples
      buildspec: codebuild/py312/examples.yml

    - identifier: code_coverage
      buildspec: codebuild/coverage.yml
